### PR TITLE
Improve assertion error message

### PR DESCRIPTION
**Pull request by bjoluc**
Sorry for this silly PR :smile:  I just found the error message "assert failed to validation error(s)" a little confusing. I think "assert failed due to validation error(s)" is a bit clearer.

### CODE REVIEW

**Comment by mtvx** [comment]
Indeed. Or it could even be just "assert failed due to:". Anyway, this is already better, thanks! :)

(Sorry for the late reply, I have no idea why Github doesn't send me email notifications of this repository. I get notified for all the repositories I'm watching, but the one where I'm actually maintainer doesn't get notified. Crazy. Randomly happened to notice your PR.)

**Comment by mtvx** [comment]
Seems like Tarvis builds are not being triggered, I need to check that...

**Comment by mtvx** [comment]
I think there were some auth issues after a long period of inactivity. Travis had actually triggered, but would not report status back.

Could you rebase? I want to be sure it works for other users, too, and not just me :|

**Comment by bjoluc** [comment]
> Crazy. Randomly happened to notice your PR

Glad you discovered it anyway!  :tada:

> Could you rebase? I want to be sure it works for other users, too, and not just me :|

Sure thing!

**Comment by mtvx** [comment]
Seems like it worked this time 👍

**Comment by bjoluc** [comment]
Thanks a lot!

**Comment by mtvx** [comment]
Released this (and couple of internal boilerplate adjustments) in 1.2.0 🌷

**Pull request merged**
